### ISSUE TITLE
IP address MQTT Gateway

### ISSUE THREAD

**Issue by alper-t** [se02035/azure-iot-suite-mqtt#1]
Hi,

I have read the instructions on:
https://azure.microsoft.com/en-us/documentation/articles/iot-hub-mqtt-support/
but it doesn't say what IP address the Azure broker is on.
I couldn't find it in the code here on github either.

Right now, I use Mosquitto broker, which looks like this in my Arduino code:
mqtt.setServer("test.mosquitto.org", 1883);

What do I change that to?

**Comment by se02035** [comment]
Azure IoT Hub supports MQTT (since Feb 2016). So you can directly communicate with the IoT Hub without an additional Azure Protocol Gateway (what I described here - this was required before the IoT Hub supported MQTT natively). The IoT Hubs's CNAME is "{your hub name}.azure-devices.net" (as described in the blog article mentioned in your post).
